[workspace]
    members =["crates/rubiks-cube", "crates/rubiks-cube-cli", "crates/twisty-puzzles-py"]
    resolver="3"

    [workspace.package]
        edition   ="2024"
        license   ="MIT"
        readme    ="README.md"
        repository="https://github.com/Iurig/rubiks"

[profile.test]
    debug           ="line-tables-only"
    debug-assertions=true
    incremental     =true
    inherits        ="release"
    overflow-checks =true
